config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_scope :user do
    get 'forget', to: 'users/passwords#forget'
    patch 'update_password', to: 'users/passwords#update_password'
    post '/login_validate', to: 'users/sessions#user_validate'
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'


  resources :properties do
  end
  resources :nests do
  end
  resources :domains do
  end

  resources :controls, :only => [:index]
  resources :templates do
    get :produce, :on => :member
  end

  resources :nlps do
    collection do
      post 'analyze'
    end
  end

  resources :notices
  resources :articles do
    get :export, :on => :collection
    get :main_image, :on => :member
    get :detail_image, :on => :member
  end

  resources :ocrs do
    post :analyze, :on => :collection
  end

  resources :subunits

  resources :statistics, :only => [:index] do
    get :line, :on => :collection
    get :series, :on => :collection
    get :column, :on => :collection
    get :pie, :on => :collection
    get :bar, :on => :collection
    get :area, :on => :collection
    get :scatter, :on => :collection
  end

  resources :systems, :only => [] do
    get :send_confirm_code, :on => :collection
  end

  resources :users, :only => []  do
    get :center, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
    get :mobile_authc_new, :on => :member
    post :mobile_authc_create, :on => :member
    get :mobile_authc_status, :on => :member
  end

  resources :orders, :only => [:new, :create] do
    get :pay, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
  end

  resources :tasks, :only => [] do
    get :invite, :on => :collection
  end

  resources :accounts, :only => [:edit, :update] do
    get :recharge, :on => :collection 
    get :info, :on => :collection
    get :status, :on => :collection
  end

  resources :roles

  resources :spiders do
    get :start, :on => :member
  end
  resources :selectors
  resources :products do
    get :download_append, :on => :member
    post :upload, :on => :member
  end
  resources :flower

  root :to => 'home#index'
end

app/models/spider.rb
class Spider < ActiveRecord::Base
  #serialize :header, Hash

  has_many :selectors, :dependent => :destroy
  accepts_nested_attributes_for :selectors, reject_if: :all_blank, allow_destroy: true


end



# == Schema Information
#
# Table name: spiders
#
#  id           :integer         not null, primary key
#  link         :string          default(""), not null
#  doc_save     :boolean         default("t"), not null
#  doc_parse    :boolean         default("t"), not null
#  header       :text
#  cookie       :string          default(""), not null
#  agent        :string          default(""), not null
#  content_type :string          default(""), not null
#  page         :string          default(""), not null
#  file         :string          default(""), not null
#  referer      :string          default(""), not null
#  host         :string          default(""), not null
#  redirection  :string          default(""), not null
#  created_at   :datetime        not null
#  updated_at   :datetime        not null
#

app/controllers/spiders_controller.rb
#require "spider_tool"
load "spider_tool.rb"

class SpidersController < ApplicationController
  layout "application_control"
  #before_filter :authenticate_user!
  #load_and_authorize_resource


  def start 
    @spider = Spider.find(params[:id])
    spider_tool = SpiderTool.new
    spider_tool.process(@spider) 
    redirect_to @spider
  end
   
  def index
    @spiders = Spider.all
  end
   

   
  def show
    @spider = Spider.find(params[:id])
  end
   

   
  def new
    @spider = Spider.new
    
    @spider.selectors.build
    
  end
   

   
  def create
    @spider = Spider.new(spider_params)
    #@spider.user = current_user
    if @spider.save
      redirect_to @spider
    else
      render :new
    end
  end
   

   
  def edit
    @spider = Spider.find(params[:id])
  end
   

   
  def update
    @spider = Spider.find(params[:id])
    if @spider.update(spider_params)
      redirect_to spider_path(@spider) 
    else
      render :edit
    end
  end
   

   
  def destroy
    @spider = Spider.find(params[:id])
    @spider.destroy
    redirect_to :action => :index
  end
   

  private
    def spider_params
      params.require(:spider).permit( :link, :cookie, :header, :agent, :doc_parse, :content_type, :page, :file, :referer, :doc_save, :host, :redirection, selectors_attributes: selector_params)
    end
  
  
    def selector_params
      [:id, :name, :category, :title]
    end
  
end

app/helpers/spiders_helper.rb
module SpidersHelper

  def options_for_content_type
    [
      ["application/x-www-form-urlencoded", "application/x-www-form-urlencoded"]
    ]
  end                                            

  def options_for_agent
    [
      ["chrome", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/63.0.3239.84 Chrome/63.0.3239.84 Safari/537.36"]
    ]
  end                                            

  def options_for_spider_category
    {
      Setting.selectors.categories.text.info => Setting.selectors.categories.text.value,
      Setting.selectors.categories.attr.info => Setting.selectors.categories.attr.value,
      Setting.selectors.categories.img.info => Setting.selectors.categories.img.value
    }
  end
end  

app/views/spiders/_form.html.haml
.container-fluid
  .row.justify-content-sm-center
    .col-sm-12
      = form_for @spider do |f|
        - if @spider.errors.any?
          #error_explanation
            %h2= "#{pluralize(@spider.errors.count, "error")} prohibited this buyer from being saved:"
            %ul
              - @spider.errors.full_messages.each do |msg|
                %li= msg
      
        .form-group.row
          = f.label Setting.spiders.link, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :link, :class => "form-control"
        .form-group.row
          = f.label Setting.spiders.page, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :page, :class => "form-control", :placeholder => "1-5"

        .form-group.row
          = f.label "是否要将请求的网页保存起来", :class => "col-sm-4 text-right"
          .col-sm-8
            .form-check.form-check-inline
              = f.radio_button :doc_save, Setting.systems.status_en_yes, :class => "form-check-input", :checked => "checked"
              = f.label Setting.systems.status_yes, :class => "form-check-label"
            .form-check.form-check-inline
              = f.radio_button :doc_save, Setting.systems.status_en_no, :class => "form-check-input"
              = f.label Setting.systems.status_no, :class => "form-check-label"
          
        .form-group.row
          = f.label "是否解析网页", :class => "col-sm-4 text-right"
          .col-sm-8
            .form-check.form-check-inline
              = f.radio_button :doc_parse, Setting.systems.status_en_yes, :class => "form-check-input", :checked => "checked"
              = f.label Setting.systems.status_yes, :class => "form-check-label"
            .form-check.form-check-inline
              = f.radio_button :doc_parse, Setting.systems.status_en_no, :class => "form-check-input"
              = f.label Setting.systems.status_no, :class => "form-check-label"
          
        .form-group.row
          = f.label Setting.spiders.cookie, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :cookie, :class => "form-control"
          
        .form-group.row
          = f.label Setting.spiders.agent, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.select :agent, options_for_agent, {:include_blank=>true}, {:class=>"form-control"}
        .form-group.row
          = f.label Setting.spiders.content_type, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.select :content_type, options_for_content_type, {:include_blank=>true}, {:class=>"form-control"}
        .form-group.row
          = f.label Setting.spiders.referer, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :referer, :class => "form-control"
          
        .form-group.row
          = f.label Setting.spiders.host, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :host, :class => "form-control"
          
        .form-group.row
          = f.label Setting.spiders.redirection, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :redirection, :class => "form-control"
          
        .form-group.row
          = f.label "请求头", :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_area :header, :class => "form-control", :rows => "5"
          
        -#
          .form-group.row
            = f.label "文件", :class => "col-sm-3 text-right"
            .col-sm-9
              = f.text_area :file, :class => "form-control", :rows => "5"
      
      
        .form-group.row
          = f.label "选择器", :class => "col-sm-1 control-label"
          .col-sm-11
            = f.fields_for :selectors do |selector|
              = render 'selector_fields', f: selector 
            .links
              = link_to_add_association "添加", f, :selectors, :class => "btn btn-success"
      
        .form-group.row
          .col-sm-3.offset-sm-2
            = f.submit '保存', :class => "btn btn-success"
          .col-sm-3.offset-sm-1
            = link_to '返回', spiders_path, :class => "btn btn-danger"

app/views/spiders/_selector_fields.html.haml
.nested-fields
  .form-group
    .field.d-inline
      .form-group.row
        .col-sm-6
          = f.text_field :name, :class => "form-control", :placeholder => Setting.selectors.name
        .col-sm-2
          = f.text_field :title, :class => "form-control", :placeholder => "选文本就填导出的文件名,选属性就填属性名" 
        
        .col-sm-2
          .form-group.row
            = f.label Setting.selectors.category, :class => "col-sm-3 text-right"
            .col-sm-9
              = f.select :category, options_for_spider_category, {:include_blank => false}, {:class => "form-control"}
        .col-sm-1
          = link_to_remove_association "删除", f, :class => "btn btn-danger btn-sm d-inline"

app/views/spiders/edit.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  = render 'form'

= render "layouts/control_panel"

app/views/spiders/index.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  .container-fluid.p-0
    .row
      .col-md-12
        %table.text-center.table-bordered.table-sm{:'data-toggle' => "table", :"data-pagination"=>"true", :"data-search" => "true",:'data-advanced-search'=>"true", :'data-id-table'=>"advancedTable"}
          %thead.thead-light
            %tr
              %th{:scope => "col"} #
            
              %th{:scope => "col"}
                = Setting.spiders.link
              %th{:scope => "col"}
          %tbody
            - @spiders.each_with_index do |spider, index|
              %tr
                %td{:scope => "row"}
                  = index+1
              
                %td
                  = spider.link
                %td
                  .container-fluid
                    .row
                      = link_to spider_path(spider), :class => "text-info col" do
                        = fa_icon "search"
                      = link_to edit_spider_path(spider), :class => "text-success col" do
                        = fa_icon "edit"
                      = link_to spider, :method => :delete, :data => {:confirm => "确定删除吗?"}, :class => "text-danger col" do
                        = fa_icon "trash"
                      = link_to start_spider_path(spider), :class => "text-primary col" do
                        = fa_icon "wrench"

= render "layouts/control_panel"

app/views/spiders/new.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  = render 'form'

= render "layouts/control_panel"

app/views/spiders/show.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  .container-fluid
    .row
      .col-md-12
        %table.table.text-center.table-bordered
          %thead
            %tr
            
              %th 
                = Setting.spiders.link
              %th 
                = Setting.spiders.cookie
              %th 
                = Setting.spiders.agent
              %th 
                = Setting.spiders.content_type
              %th 
                = Setting.spiders.page
              %th 
                = Setting.spiders.file
              %th 
                = Setting.spiders.referer
              %th 
                = Setting.spiders.host
              %th 
                = Setting.spiders.redirection
          %tbody
            %tr
            
              %td
                = @spider.link
              %td
                = @spider.cookie
              %td
                = @spider.agent
              %td
                = @spider.content_type
              %td
                = @spider.page
              %td
                = @spider.file
              %td
                = @spider.referer
              %td
                = @spider.host
              %td
                = @spider.redirection
    

= render "layouts/control_panel"