config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_scope :user do
    get 'forget', to: 'users/passwords#forget'
    patch 'update_password', to: 'users/passwords#update_password'
    post '/login_validate', to: 'users/sessions#user_validate'
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'


  resources :properties do
  end
  resources :nests do
  end
  resources :domains do
  end

  resources :controls, :only => [:index]
  resources :templates do
    get :produce, :on => :member
  end

  resources :nlps do
    collection do
      post 'analyze'
    end
  end

  resources :notices
  resources :articles do
    get :export, :on => :collection
    get :main_image, :on => :member
    get :detail_image, :on => :member
  end

  resources :ocrs do
    post :analyze, :on => :collection
  end

  resources :subunits

  resources :statistics, :only => [:index] do
    get :line, :on => :collection
    get :series, :on => :collection
    get :column, :on => :collection
    get :pie, :on => :collection
    get :bar, :on => :collection
    get :area, :on => :collection
    get :scatter, :on => :collection
  end

  resources :systems, :only => [] do
    get :send_confirm_code, :on => :collection
  end

  resources :users, :only => []  do
    get :center, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
    get :mobile_authc_new, :on => :member
    post :mobile_authc_create, :on => :member
    get :mobile_authc_status, :on => :member
  end

  resources :orders, :only => [:new, :create] do
    get :pay, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
  end

  resources :tasks, :only => [] do
    get :invite, :on => :collection
  end

  resources :accounts, :only => [:edit, :update] do
    get :recharge, :on => :collection 
    get :info, :on => :collection
    get :status, :on => :collection
  end

  resources :roles

  resources :spiders do
    get :start, :on => :member
  end
  resources :selectors
  resources :products do
    get :download_append, :on => :member
    post :upload, :on => :member
  end
  resources :flower

  root :to => 'home#index'
end

app/models/article.rb
class Article < ActiveRecord::Base

  has_many :enclosures, :dependent => :destroy
  accepts_nested_attributes_for :enclosures, reject_if: :all_blank, allow_destroy: true


  has_many :article_contents, :dependent => :destroy
  accepts_nested_attributes_for :article_contents, reject_if: :all_blank, allow_destroy: true


end


# == Schema Information
#
# Table name: articles
#
#  id         :integer         not null, primary key
#  lang       :string          default(""), not null
#  title      :string          default(""), not null
#  vol        :string          default(""), not null
#  desc       :string          default(""), not null
#  category   :text
#  address    :string          default(""), not null
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  layout "application_control"
  #before_filter :authenticate_user!
  #load_and_authorize_resource

  PUBLIC_FOLDER = File.join(Rails.root, "public")
  ARTICLE_FOLDER = PUBLIC_FOLDER + "/articles/"
   
  def index
    @articles = Article.all
  end
   

   
  def show
    @article = Article.find(params[:id])
  end
   

   
  def new
    @article = Article.new
    
    @article.article_contents.build
    
  end
   

   
  def create
    @article = Article.new(article_params)
    #@article.user = current_user
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end
   

  def edit
    @article = Article.find(params[:id])
  end
   

   
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article) 
    else
      render :edit
    end
  end
   
  def export
    articles = Article.all
    vxlogo = "lib/tasks/data/coursefolder/assets"
    articles.each do |article|
      folder = ARTICLE_FOLDER + "/" + article.lang + "/"
      FileUtils.mkdir(folder) unless File.directory?(folder)
      unless File.directory?(folder + "assets")
        FileUtils.cp_r(vxlogo, folder) 
        target_file = folder + 'README.md'
        title_one = "<h1>全套最新" + article.lang + "视频教程</h1>" 
        badge = "<img src='https://img.shields.io/badge/download-5.3K-brightgreen'/><a href='assets/vxlogo.jpg'><img src='https://img.shields.io/badge/author-%E6%9D%BE%E9%BC%A0-blue'/></a><img src='https://img.shields.io/badge/licenese-crystal-green'/><br/>"
        intro = "<img src='assets/about.jpg'/><img src='assets/content.jpg'/><img src='assets/route.jpg'/><br/>"
        md = ReverseMarkdown.convert title_one + badge + intro 
        File.open(target_file, 'a+') do |f|
          f.write(md)
        end
      end
      export_articles(article, folder)
      produce_readme(article, folder)
    end
    redirect_to articles_path
  end

  def main_image
    @article = Article.find(params[:id])
    @imgs = @article.enclosures
  end

  def detail_image
    @article = Article.find(params[:id])
  end
   
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to :action => :index
  end
   

  private
    def article_params
      params.require(:article).permit( :title, :lang, :vol, :desc, :category, :address , enclosures_attributes: enclosure_params, article_contents_attributes: article_content_params)
    end
  
    def enclosure_params
      [:id, :file, :_destroy]
    end
  
  
    def article_content_params
      [:id, :title, :desc, :tag]
    end
  
  def export_articles(article, folder)
    ctns = article.article_contents
    ctg = article.category.gsub("\n", "  \n")
    title = '<h1>' + article.title + '视频教程</h1>'
  
    address = '<blockquote>网盘地址:  ' + article.address + '</blockquote>'
    ctn_str = "<h2>加公众号 获取更多新教程</h2><img src='assets/vxlogo.jpg'/>"
    ctns.each do |ctn|
      ctn_str += '<h2>' + ctn.title + '</h2>'
      ctn_str += '<p>' + ctn.desc.gsub("\r\n", "</p><p>") + '</p>'
    end
    
    ctn_title = '<h2>教程目录大纲</h2>'
    md = ReverseMarkdown.convert title + address + ctn_str + ctn_title
  
    target_file = folder + article.title + '.md'
    File.open(target_file, 'w+') do |f|
      f.write(md + ctg)
    end
  end
  
  def produce_readme(article, folder)
    title = '<h2>' + article.title + '视频教程' + "--" + article.vol + '--<a href="' + article.title + '.md">' + '目录大纲</a>' + '</h2>'
    address = '<blockquote>网盘地址:  ' + article.address + '</blockquote>'
  
    md = ReverseMarkdown.convert title + address 
  
    target_file = folder + 'README.md'
    File.open(target_file, 'a+') do |f|
      f.write(md)
    end
  end
end

app/views/articles/_article_content_fields.html.haml
.nested-fields
  .form-group
    .field.d-inline
      .form-group.row
        = f.label Setting.article_contents.title, :class => "col-sm-3 text-right"
        .col-sm-9
          = f.text_field :title, :class => "form-control"
        
      .form-group.row
        = f.label Setting.article_contents.desc, :class => "col-sm-3 text-right"
        .col-sm-9
          = f.text_area :desc, :class => "form-control", :rows => "5"
        
      .form-group.row
        = f.label Setting.article_contents.tag, :class => "col-sm-3 text-right"
        .col-sm-9
          = f.select :tag, options_for_title_tag, {:include_blank=>false}, {:class=>"form-control"}
    = link_to_remove_association "删除", f, :class => "btn btn-danger btn-sm d-inline"

app/views/articles/_enclosure_fields.html.haml
.nested-fields
  .form-group
    .field.d-inline
      = f.file_field :file, :accept => "image/png, image/jpeg, image/gif"
    = link_to_remove_association "删除", f, :class => "btn btn-danger btn-sm d-inline"

app/views/articles/_form.html.haml
.container-fluid
  .row.justify-content-sm-center
    .col-sm-12
      = form_for @article do |f|
        - if @article.errors.any?
          #error_explanation
            %h2= "#{pluralize(@article.errors.count, "error")} prohibited this buyer from being saved:"
            %ul
              - @article.errors.full_messages.each do |msg|
                %li= msg
        .form-group.row
          = f.label Setting.articles.lang, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :lang, :class => "form-control"
          
      
        .form-group.row
          = f.label Setting.articles.title, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :title, :class => "form-control"
          
        .form-group.row
          = f.label Setting.articles.address, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :address, :class => "form-control"
          
        .form-group.row
          = f.label Setting.articles.category, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_area :category, :class => "form-control", :rows => "10"
          
        .form-group.row
          = f.label Setting.articles.vol, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_field :vol, :class => "form-control"

        .form-group.row
          = f.label Setting.articles.desc, :class => "col-sm-3 text-right"
          .col-sm-9
            = f.text_area :desc, :class => "form-control", :rows => "10"
      
        .form-group.row
          = f.label "Logo", :class => "col-sm-1 control-label"
          .col-sm-11
            = f.fields_for :enclosures do |enclosure|
              = render 'enclosure_fields', f: enclosure
            .links
              = link_to_add_association "添加文件", f, :enclosures, :class => "btn btn-success"
      
      
        .form-group.row
          = f.label "文章内容", :class => "col-sm-1 control-label"
          .col-sm-11
            = f.fields_for :article_contents do |article_content|
              = render 'article_content_fields', f: article_content 
            .links
              = link_to_add_association "添加", f, :article_contents, :class => "btn btn-success"
      
        .form-group.row
          .col-sm-3.offset-sm-2
            = f.submit '保存', :class => "btn btn-success"
          .col-sm-3.offset-sm-1
            = link_to '返回', articles_path, :class => "btn btn-danger"

app/views/articles/detail_image.html.haml
%button.btn.btn-primary#export-detail-btn
  下载图片
.container
  .detail-ctn-750.mb-5
    .row
      - @article.category.scan(/(.+)\.(?:rmvb|avi|mp4|wmv)/i) do |c|
        .col-6.text-truncate
          = image_tag "xunlei.jpg", :width => "30px"
          = c[0]

  .detail-ctn-750.mb-5
    .row
      - @article.category.scan(/(.+)\.(?:rmvb|avi|mp4|wmv)/i) do |c|
        .col-6.text-truncate
          = image_tag "bfyy.jpg", :width => "30px"
          = c[0]
  .detail-ctn-750.mb-5.bg-BCD
    = @article.category.gsub(/\n/, '<br/>').html_safe

app/views/articles/edit.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  = render 'form'

= render "layouts/control_panel"

app/views/articles/index.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  .container-fluid.p-0
    .row
      .col-md-2
        = link_to "生成结构目录", export_articles_path, :class => "btn btn-block btn-primary"
      .col-md-12
        %table.text-center.table-bordered.table-sm{:'data-toggle' => "table", :"data-pagination"=>"true", :"data-search" => "true",:'data-advanced-search'=>"true", :'data-id-table'=>"advancedTable"}
          %thead.thead-light
            %tr
              %th{:scope => "col"} #
            
              %th{:scope => "col"}
                = Setting.articles.title
              %th{:scope => "col"}
                = Setting.articles.category
              %th{:scope => "col"}
                = Setting.articles.address
              %th{:scope => "col"}
          %tbody
            - @articles.each_with_index do |article, index|
              %tr
                %td{:scope => "row"}
                  = index+1
              
                %td
                  = article.title
                %td
                  = truncate(article.category)
                %td
                  = article.address
                %td
                  .container-fluid
                    .row
                      = link_to article_path(article), :class => "text-info col" do
                        = fa_icon "search"
                      = link_to edit_article_path(article), :class => "text-success col" do
                        = fa_icon "edit"
                      = link_to "主图", main_image_article_path(article), :class => "text-success col"
                      = link_to "详情图", detail_image_article_path(article), :class => "text-success col"

= render "layouts/control_panel"

app/views/articles/main_image.html.haml
%button.btn.btn-primary#export-image-btn
  下载图片
.container.my-5
  #main-image-first.main-image-ctn.text-center.border.mb-5
    .height-100.bg-dark.text-white.d-flex.justify-content-around.align-items-center
      - if @imgs[0]
        = image_tag @imgs[0].file_url, :width => "100px"
      %h1.article-title.font-weight-bold
        
        = @article.title
        零基础到实战视频
    .height-100.d-flex.justify-content-center.align-items-center.px-3
      %h2.article-vol.bg-F8E5.p-3.w-100.font-weight-bold.shadow
        = @article.vol
        视频教程, 无垃圾, 无重复
    .height-100.article-info.px-3
      .row
        .col-10
          %ul.text-723.text-left{:type => "square"}
            %li.mb-3
              %h3.font-weight-bold
                视频分类详细,学习路线规划清晰
            %li
              %h3.font-weight-bold
                教学视频+软件开发工具+笔记+源代码
        .col-2
          = image_tag '2020.jpg', :class => "img-thumbnail w-5"

    .height-400.article-desc.mx-4.bg-2D2.text-truncate
      %h3.text-wrap.text-white.p-4
        - @article.desc.split("、").shuffle.each do |d|
          = d + " | "
        = "..."
    .height-100.article-footer.bg-danger.d-flex.align-items-center.justify-content-center
      %h1.text-white.font-weight-bold.py-3
        = @article.title
        工程师必学课程,主流开发技术

  #main-image-two.main-image-ctn.text-center.border.mb-5.bg-2a3
    .height-100.bg-dark.text-white.d-flex.justify-content-around.align-items-center
      - if @imgs[1]
        = image_tag @imgs[1].file_url, :width => "100px"
      %h1.article-title.font-weight-bold
        零基础自学
        = @article.title
        视频
    .height-100.d-flex.justify-content-around.align-items-center.px-3
      %h2.article-vol.bg-01B.w-100.p-3.text-white.font-weight-bold.shadow
        2020专为零基础同学入编程大坑准备
    .height-500.article-desc.mx-4.bg-4F9.text-white.text-truncate
      %h2
        基础入门>框架开发>项目实战>求职笔试面试
      %hr.border.border-white
      %h3.text-wrap.text-white.p-2
        - @article.desc.split("、").shuffle.each do |d|
          = d + ",  "
        = "..."
    .height-100.article-footer.bg-186.d-flex.align-items-center.justify-content-center
      %h1.text-white.font-weight-bold.py-3
        承接网站、app、小程序、爬虫开发

  #main-image-three.main-image-ctn.text-center.border.mb-5.bg-133
    .height-100.bg-dark.text-white.d-flex.justify-content-around.align-items-center
      %h1.article-title.font-weight-bold
        2020零基础>自学>工程师
      - if @imgs[2]
        = image_tag @imgs[2].file_url, :width => "100px"
    .height-100.text-white.d-flex.justify-content-around.align-items-center.px-3
      %h2.w-100.article-vol.bg-01B.p-3.font-weight-bold.shadow
        一套视频全面完整学习
        = @article.title
        开发
    .height-100.text-white.d-flex.justify-content-around.align-items-center.px-3
      %h2.w-100.article-vol.bg-ffc.p-3.font-weight-bold.text-dark.shadow
        = @article.title
        0到工程师之路
    .height-400.article-desc.mx-4.bg-912.text-white.text-truncate
      %h2
        主流开发技术、企业实战开发需要必知必会技术
        %br
        教学视频+源码+笔记+开发工具
      %hr.my-0.border.border-white
      %h3.text-wrap.text-white.px-2
        - @article.desc.split("、").shuffle.each do |d|
          = d + "/"
        = "..."
    .height-100.article-footer.bg-512.d-flex.align-items-center.justify-content-center
      %h1.text-white.font-weight-bold.py-3
        承接网站、app、小程序、爬虫开发

  #main-image-four.main-image-ctn.text-center.border.mb-5.bg-2a3c
    .height-100.bg-E34.text-white.d-flex.justify-content-around.align-items-center
      %h1.article-title.font-weight-bold
        2020 零基础轻松自学
        = @article.title
      - if @imgs[3]
        = image_tag @imgs[3].file_url, :width => "100px"
    .height-100.text-white.d-flex.justify-content-around.align-items-center.px-3
      %h2.w-100.text-white.article-vol.bg-77b.p-3.font-weight-bold.shadow
        = @article.title
        工程师必学课程、主流开发技术
    .height-100
      %h2.text-white.article-vol.bg-5b9.mx-auto.w-75.p-3.font-weight-bold.shadow
        视频/源码/电子书/开发软件
    .height-400.article-desc.mx-4.bg-0d3.text-white.text-truncate
      %h3.text-wrap.text-white.p-2
        - @article.desc.split("、").shuffle.each do |d|
          = d + "+"
        = "..."
    .height-100.article-footer.bg-512.d-flex.align-items-center.justify-content-center
      %h1.text-white.font-weight-bold.py-3
        零基础学习、学习路线规划详细清晰

  #main-image-five.main-image-ctn.text-center.border.mb-5.bg-2720
    .height-100.text-white.d-flex.justify-content-around.align-items-center
      - if @imgs[4]
        = image_tag @imgs[4].file_url, :width => "100px"
      %h1.article-title.font-weight-bold
        全套
        = @article.title
        视频教程
    .height-100.d-flex.justify-content-around.align-items-center.px-3
      %h1.w-100.article-vol.bg-ffc.p-3.font-weight-bold.shadow
        2020完全0基础入门到实战
    .height-100.d-flex.justify-content-around.align-items-center.px-3
      %h2.w-100.text-white.article-vol.bg-5b9.p-3.font-weight-bold.shadow
        教学视频、源码、开发笔记、电子书、开发工具
    .height-400.article-desc.mx-4.border.text-white.text-truncate
      %h3.text-wrap.text-white.p-2
        - @article.desc.split("、").shuffle.each do |d|
          = d + "、"
        = "..."
    .height-100.article-footer.bg-de0.d-flex.align-items-center.justify-content-center
      %h2.text-white.font-weight-bold.py-3
        开发者群+2900套网站模板免费下载+教程免费持续更新

  #main-image-six.main-image-ctn.text-center.border.mb-5.bg-gtx
    .height-100.text-white.d-flex.justify-content-around.align-items-center.bg-255165-opacity
      - if @imgs[5]
        = image_tag @imgs[5].file_url, :width => "100px"
      %h1.article-title.font-weight-bold
        全面系统自学
        = @article.title
        视频教程
    .height-100.d-flex.justify-content-around.align-items-center.px-3
      %h1.w-100.article-vol.bg-ffc-opacity.p-3.font-weight-bold.shadow
        2020完全0基础入门到实战
    .height-100.d-flex.justify-content-around.align-items-center.px-3
      %h2.w-100.text-white.article-vol.bg-5b9.p-3.font-weight-bold.shadow
        教学视频、源码、开发笔记、电子书、开发工具
    .height-400.bg-dark-opacity.article-desc.mx-4.border.text-white.text-truncate
      %h3.text-wrap.text-white.p-2
        - @article.desc.split("、").shuffle.each do |d|
          = d + " | "
        = "..."
    .height-100.article-footer.bg-de0.d-flex.align-items-center.justify-content-center
      %h1.text-white.font-weight-bold.py-3
        本人提供软件开发服务,有需求可联系我

  #main-image-seven.main-image-ctn.text-center.border.mb-5
    .height-100.d-flex.justify-content-around.align-items-center.border-3
      - if @imgs[6]
        = image_tag @imgs[6].file_url, :width => "100px"
      %h1.article-title.font-weight-bold
        = @article.title
        零基础>>自学>>工程师
    .height-100.d-flex.justify-content-around.align-items-center.px-3
      %h1.w-100.article-vol.p-3.mb-0.font-weight-bold.text-e85
        一套教程全面完整学通
        = @article.title
    .height-100.d-flex.justify-content-around.align-items-center.px-3
      %h1.text-528.w-100.article-vol.p-3
        = @article.vol 
        教学视频+源码+电子书+开发工具
    .height-400.article-desc.mx-4.border-zi.text-white.text-truncate
      %h3.text-wrap.text-630.p-2
        - @article.desc.split("、").shuffle.each do |d|
          = d + ", "
        = "..."
    .height-100.article-footer.bg-BCD2.d-flex.align-items-center.justify-content-center
      %h1.text-white.font-weight-bold.py-3
        本人提供软件开发服务,有需求可联系我

  #main-image-eight.main-image-ctn.text-center.border.mb-5
    .height-100.d-flex.justify-content-around.align-items-center.border-4
      - if @imgs[7]
        = image_tag @imgs[7].file_url, :width => "100px"
      %h1.article-title.font-weight-bold.text-info
        = @article.title
        零基础>>自学>>实战开发
    .height-100.d-flex.justify-content-around.align-items-center.px-3.bg-dc5131
      %h1.w-100.article-vol.p-3.mb-0.font-weight-bold.text-00f
        全套
        = @article.title
        全面系统详细视频教程
    .height-100.d-flex.justify-content-around.align-items-center.px-3
      %h1.text-dc5131.w-100.article-vol.p-3
        = @article.vol 
        教学视频,源码,课件,软件工具
    .height-400.article-desc.mx-4.text-white.text-truncate
      %h3.text-wrap.text-630.p-2
        - @article.desc.split("、").shuffle.each do |d|
          = d + " | "
        = "..."
    .height-100.article-footer.bg-dc5131.d-flex.align-items-center.justify-content-center
      %h1.text-white.font-weight-bold.py-3
        企业主流开发技术+教程持续更新

app/views/articles/new.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  = render 'form'

= render "layouts/control_panel"

app/views/articles/show.html.haml
- provide(:title, t('.title'))

- content_for :main_body do
  .container-fluid
    .row
      .col-md-12
        %table.table.text-center.table-bordered
          %thead
            %tr
            
              %th 
                = Setting.articles.title
              %th 
                = Setting.articles.category
              %th 
                = Setting.articles.address
          %tbody
            %tr
            
              %td
                = @article.title
              %td
                = @article.category
              %td
                = @article.address
    
      .col-md-12
      -#
        - @article.enclosures.each do |e|
          = image_tag e.file_url(:small_width)
    

= render "layouts/control_panel"