config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  devise_scope :user do
    get 'forget', to: 'users/passwords#forget'
    patch 'update_password', to: 'users/passwords#update_password'
    post '/login_validate', to: 'users/sessions#user_validate'
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'


  resources :properties do
  end
  resources :nests do
  end
  resources :domains do
  end

  resources :controls, :only => [:index]
  resources :templates do
    get :produce, :on => :member
  end

  resources :nlps do
    collection do
      post 'analyze'
    end
  end

  resources :notices
  resources :articles do
    get :export, :on => :collection
    get :main_image, :on => :member
    get :detail_image, :on => :member
  end

  resources :ocrs do
    post :analyze, :on => :collection
  end

  resources :subunits

  resources :statistics, :only => [:index] do
    get :line, :on => :collection
    get :series, :on => :collection
    get :column, :on => :collection
    get :pie, :on => :collection
    get :bar, :on => :collection
    get :area, :on => :collection
    get :scatter, :on => :collection
  end

  resources :systems, :only => [] do
    get :send_confirm_code, :on => :collection
  end

  resources :users, :only => []  do
    get :center, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
    get :mobile_authc_new, :on => :member
    post :mobile_authc_create, :on => :member
    get :mobile_authc_status, :on => :member
  end

  resources :orders, :only => [:new, :create] do
    get :pay, :on => :collection
    get :alipay_return, :on => :collection
    post :alipay_notify, :on => :collection
  end

  resources :tasks, :only => [] do
    get :invite, :on => :collection
  end

  resources :accounts, :only => [:edit, :update] do
    get :recharge, :on => :collection 
    get :info, :on => :collection
    get :status, :on => :collection
  end

  resources :roles

  resources :spiders do
    get :start, :on => :member
  end
  resources :selectors
  resources :products do
    get :download_append, :on => :member
    post :upload, :on => :member
  end
  resources :flower

  root :to => 'home#index'
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  layout "application_control"
  before_action :authenticate_user!

  def index
    @line_title = chart_title("标题", "图例", "x轴标题", "y轴标题", "#007bff")
    @column_title = chart_title("标题", "图例", "x轴标题", "y轴标题", "#e83e8c")
    @bar_title = chart_title("标题", "图例", "x轴标题", "y轴标题", "#28a745")
    @area_title = chart_title("标题", "图例", "x轴标题", "y轴标题", "#fd7e14")
    @scatter_title = chart_title("标题", "图例", "x轴标题", "y轴标题", "#17a2b8")

    @pie_title = chart_title("标题", "图例", "x轴标题", "y轴标题" )
  end
   
  def line
    render json: Account.group(:user_id).count
  end

  def column
    render json: Account.group(:user_id).count
  end

  def pie 
    render json: Account.group(:user_id).count
  end

  def bar 
    render json: Account.group(:user_id).count
  end

  def area 
    render json: Account.group(:user_id).count
  end

  def scatter 
    render json: Account.group(:user_id).count
  end

  def series 
    #第一个group是序列,第二个group是x轴对应的值
    render json: Account.group(:coin).group(:user_id).count.chart_json
  end

  private
    def chart_title(title, label, xtitle, ytitle, *colors)
      return {
        title: title,
        label: label,
        xtitle: xtitle,
        ytitle: ytitle,
        colors: colors
      }
    end
end

app/views/statistics/index.html.haml
- provide(:title, t('.title'))

.container-fluid
  .row
    = render "layouts/control_sidebar"
    %main.col-md-9.ml-sm-auto.col-lg-10.p-3{:role => "main"}
      .card.shadow.rounded-0.mb-3
        .card-header.bg-primary.text-white.rounded-0
          = fa_icon "line-chart", text: @line_title[:title]
        .card-body
          .container-fluid.p-0
            .row
              .col-md-12
                = line_chart line_statistics_path, legend: "right", label: @line_title[:label],  title: @line_title[:title], xtitle: @line_title[:xtitle], ytitle: @line_title[:ytitle], download: {background: "#ffffff"}, colors: @line_title[:colors]
      .card.shadow.rounded-0.mb-3
        .card-header.bg-primary.text-white.rounded-0
          = fa_icon "line-chart", text: "多序列" 
        .card-body
          .container-fluid.p-0
            .row
              .col-md-12
                = line_chart series_statistics_path 
      .card.shadow.rounded-0.mb-3
        .card-header.bg-danger.text-white.rounded-0
          = fa_icon "bar-chart", text: @column_title[:title]
        .card-body
          .container-fluid.p-0
            .row
              .col-md-12
                = column_chart column_statistics_path, legend: "right", label: @column_title[:label],  title: @column_title[:title], xtitle: @column_title[:xtitle], ytitle: @column_title[:ytitle], download: {background: "#ffffff"}, colors: @column_title[:colors]
      .card.shadow.rounded-0.mb-3
        .card-header.bg-success.text-white.rounded-0
          = fa_icon "bar-chart-o", text: @bar_title[:title]
        .card-body
          .container-fluid.p-0
            .row
              .col-md-12
                = bar_chart bar_statistics_path, legend: "right", label: @bar_title[:label],  title: @bar_title[:title], xtitle: @bar_title[:xtitle], ytitle: @bar_title[:ytitle], download: {background: "#ffffff"}, colors: @bar_title[:colors]
      .card.shadow.rounded-0.mb-3
        .card-header.bg-info.text-white.rounded-0
          = fa_icon "pie-chart", text: @pie_title[:title]
        .card-body
          .container-fluid.p-0
            .row
              .col-md-12
                = pie_chart pie_statistics_path, legend: "right", label: @pie_title[:label],  title: @pie_title[:title], xtitle: @pie_title[:xtitle], ytitle: @pie_title[:ytitle], download: {background: "#ffffff"}
      .card.shadow.rounded-0.mb-3
        .card-header.bg-warning.text-white.rounded-0
          = fa_icon "area-chart", text: @area_title[:title]
        .card-body
          .container-fluid.p-0
            .row
              .col-md-12
                = area_chart area_statistics_path, legend: "right", label: @area_title[:label],  title: @area_title[:title], xtitle: @area_title[:xtitle], ytitle: @area_title[:ytitle], download: {background: "#ffffff"}, colors:  @area_title[:colors]
      .card.shadow.rounded-0.mb-3
        .card-header.bg-info.text-white.rounded-0
          = fa_icon "circle", text: @scatter_title[:title]
        .card-body
          .container-fluid.p-0
            .row
              .col-md-12
                = scatter_chart scatter_statistics_path, legend: "right", label: @scatter_title[:label],  title: @scatter_title[:title], xtitle: @scatter_title[:xtitle], ytitle: @scatter_title[:ytitle], download: {background: "#ffffff"}, colors: @scatter_title[:colors]